FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY dyn_opt/dyn_opt.py ./dyn_opt/
COPY dyn_opt/app.py ./app.py

COPY risk_limits/portfolio_risk.py ./risk_limits/portfolio_risk.py
COPY risk_limits/position_risk.py ./risk_limits/position_risk.py

COPY shared_functions/_logging.py ./shared_functions/_logging.py

COPY risk_measures/risk_functions.py ./risk_measures/risk_functions.py

ENV PYTHONPATH=/app

CMD [ "python", "app.py"]